# Generated by Django 3.2.8 on 2021-10-15 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=45, verbose_name='Password')),
                ('rol', models.CharField(max_length=45, verbose_name='Rol')),
                ('nombre', models.CharField(max_length=15, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=15, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('estado', models.CharField(max_length=45, verbose_name='Estado')),
                ('telefono_viajero', models.IntegerField(verbose_name='Telefono')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vuelos',
            fields=[
                ('IdVuelo', models.AutoField(primary_key=True, serialize=False)),
                ('aerolinea', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField()),
                ('origen', models.DateField()),
                ('destino', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('sillas_disponibles', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idReserva', models.AutoField(primary_key=True, serialize=False)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idViajero', to=settings.AUTH_USER_MODEL)),
                ('numero_vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numero_vuelo', to='authApp.vuelos')),
            ],
        ),
    ]
